/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/VideosView/project/demo/demo1 copy.vue')['default']
    Demo: typeof import('./src/components/demo.vue')['default']
    Demo0: typeof import('./src/components/demo0.vue')['default']
    Demo1: typeof import('./src/components/demo1.vue')['default']
    Demo2: typeof import('./src/components/demo2.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GamesView: typeof import('./src/components/GamesView.vue')['default']
    HOME: typeof import('./src/components/HOME.vue')['default']
    Home01: typeof import('./src/components/home01.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImagesView: typeof import('./src/components/ImagesView.vue')['default']
    Project: typeof import('./src/components/project.vue')['default']
    Recommend: typeof import('./src/components/VideosView/view/recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/VideosView/sidebar.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Topview: typeof import('./src/components/VideosView/topview.vue')['default']
    Trend: typeof import('./src/components/VideosView/view/Trend.vue')['default']
    VideosView: typeof import('./src/components/VideosView.vue')['default']
  }
}
